server:
  port: 8080

spring:
  application:
    name: my-backend
  datasource:
    url: jdbc:mariadb://localhost:3306/donationDB
    username: yejin_all
    password: maria1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: donationJWTSecretForHS256Algorithm123456
    access-token-expiration: 3600000

mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


